### ISSUE TITLE
No import of x3d/wrl files possible

### ISSUE THREAD

**Issue by BujusKrachus** [Tilapiatsu/blender-Universal_Multi_Importer#3]
Description of extensions state, that x3d and wrl is supported. However no import is possible, won't even display the files in the file viewer.

Clean install of blender 4.2, with this extension.

Possibly missing an dependency extension?

**Comment by Tilapiatsu** [comment]
Hi @BujusKrachus !

Thanks for reaching out.

Actually you point out a part of the addon that was not properly exposed to the user : This addon is giving Batching capability to existing importer addons, and if one addon is not installed or enabled for some reason, usually people don't have a clue why one format is not working

So to adress that,  I've made a section in the Preferences to check the addon dependencies.

Here is how it looks:
https://github.com/user-attachments/assets/c2e7b3a4-c8c2-45a9-bead-334111e37257


Here is the modified version : 
[tila_universal_multi_importer_2.1.5_RC_AddonDependencyChecker.zip](https://github.com/user-attachments/files/16333176/tila_universal_multi_importer_2.1.5_RC_AddonDependencyChecker.zip)

Can you please : 
- uninstall the previous version
- restart blender
- install this new version
- follow the instruction in the preferences to see if it solves the issue for you

If everything is fine for you, I'll make it a proper release on extension website.

Have a good day

**Comment by BujusKrachus** [comment]
Thanks a lot for the quick response. 
Yes, now it works. And it's really nice to get the ability to manage the dependencies. Would be cool though if there would be buttons for uninstalling/updating as well, if that's even currently possible.
Another nice thing would be an indicator in the import window, which formats are currently supported/installed. Usually i'd go with an error message when importing an "invalid/unknown" file, but "unkown" files won't even get displayed in the first place.

Btw i had the x3d addon already installed (as i'm currently fixing some old bug reports), don't know why your addon wasn't working with the previous (official) version. Probably didn't register that the correspodning addon was already installed.

**Comment by Tilapiatsu** [comment]
Thanks for the confirmation !

It's nice to here your feedback ! And indeed I would have prefer a solution where it doesn't require to restart blender etc. But it is a current limitation of the addon I don't really know how to go arround it. 
To add a new format, the addon have to be unregister and register again. And once unregistered no code can run from it obvisouly as it is "virtually" not here anymore.
Thats mainly why there is the unideal process of restarting blender. But I but it is managable as user is only dealing that once.

Regarding your second point, this is something I've considered : adding message to let the user know that this or this format is invalid or unknown, but I didn't do it because it was becoming really annoying getting prompt. The addon already have a lot of settings to setup if you have many different formats in the same import.
So I've chosen to keep this part simple, to avoid too much clutter.

There is another issue open by someone else. I'm waiting for her/his confirmation and I'll make another release with this fix.
I'm closing the issue meanwhile, and i'll notify you when the release will be online.

**Comment by Tilapiatsu** [comment]
The new release is now published on both Github and Extension platform :)
